### ISSUE TITLE
Soft Focus

### ISSUE THREAD

**Issue by jcmorrow** [replayio/devtools#6590]
### Background

We currently support Focus Mode. Now, we *think* of focus mode as one thing, but in fact, it is two things: Focus mode tells the backend to load and unload particular regions of the recording using [Session.loadRegion](https://static.replay.io/protocol/tot/Session/#method-loadRegion) and [Session.unloadRegion](https://static.replay.io/protocol/tot/Session/#method-unloadRegion). This is how we think of what focus mode *is*, but there's actually some nuance here. I don't want to go into the full details because I've already [written them up elsewhere](https://www.notion.so/replayio/Loading-Region-Problems-b8dc0d03c49840f8b504e967c7ea5778), but the short version is: unloading some regions is not enough for millisecond control of your focus region, since regions are usually about half a second in length. Instead, we have to *pretend* to unload stuff that falls outside of our focus window (but still falls inside of the loaded region). I am calling this approach Soft Focus (for the 📷  nerds). Why is this important? Well, it's important for two reasons:

1) The combination of Soft Focus and region unloading can result in inconsistent results from the debugger (see the linked explainer above)
2) If point 1 were not true, if instead we never needed to actually unload sections of the recording, and instead we could just *pretend* to unload them, well then we should do that!

### Todos

- [x] add a feature flag that turns all focus into soft-focus? Some stuff will be broken but that's ok, I want to see how much is broken and what else we need to fix besides the stuff on this list.
- [x] allow some protocol methods which currently do not allow for filtering by time to filter by time
	- [x] `getHitCounts`
	- [x] `Console.findMessages`
- [x] https://github.com/RecordReplay/devtools/issues/7036
- [ ] Produce a much better `getPointNearTime` which will permit a wider release for soft focus

We need to do #7036 for Friday, but the `getPointNearTime` can be a follow-on.

**Comment by jasonLaster** [comment]
Love the branding!

re hit counts: what are your concerns with continuing to use `getHitCounts` as the default?

**Comment by jcmorrow** [comment]
> what are your concerns with continuing to use getHitCounts as the default?

Well, this just requires doing the work of allowing the endpoint to accept begin and end times. And that might end up being more involved than it sounds, because even after the recent position/location cache improvement, I don't think it's possible to say with certainty the hit counts in an arbitrary span without doing a full findAnalysisPoints of the bookend regions.

**Comment by jcmorrow** [comment]
Update: Soft focus is out behind a feature flag. Some analysis work is still ongoing (see #6591 for details), and I've added a new task around making a better `getPointNearTime` which will make wider release easier.

**Comment by jasonLaster** [comment]
@jcmorrow does the friday announcement seem tenable?

**Comment by gideonred** [comment]
This ticket has been moved to [FE-160](https://linear.app/replay/issue/FE-160/soft-focus)
